language: php
php:
    - '7.2'
    - '8.0'
notifications:
    on_success: never
    on_failure: always
cache:
 directories:
   - $HOME/.composer/cache/files
before_script:
    - composer self-update
    - composer install --prefer-source --no-interaction
    - composer dump-autoload
script:
    composer run-script test
    